<?php namespace Multiverse\Notazz\NFe;

use Multiverse\Notazz\Resource;

class ShippingVolumes extends Resource
{
    protected $DOCUMENT_FRETE_VOLUMES_QTD;
    protected $DOCUMENT_FRETE_VOLUMES_SPECIES;
    protected $DOCUMENT_FRETE_VOLUMES_NET_WEIGHT;
    protected $DOCUMENT_FRETE_VOLUMES_GROSS_WEIGHT;

    public function __construct(
        $DOCUMENT_FRETE_VOLUMES_QTD,
        $DOCUMENT_FRETE_VOLUMES_SPECIES,
        $DOCUMENT_FRETE_VOLUMES_NET_WEIGHT,
        $DOCUMENT_FRETE_VOLUMES_GROSS_WEIGHT
    )
    {
        $this->DOCUMENT_FRETE_VOLUMES_QTD = $DOCUMENT_FRETE_VOLUMES_QTD ;
        $this->DOCUMENT_FRETE_VOLUMES_SPECIES = $DOCUMENT_FRETE_VOLUMES_SPECIES ;
        $this->DOCUMENT_FRETE_VOLUMES_NET_WEIGHT = $DOCUMENT_FRETE_VOLUMES_NET_WEIGHT ;
        $this->DOCUMENT_FRETE_VOLUMES_GROSS_WEIGHT = $DOCUMENT_FRETE_VOLUMES_GROSS_WEIGHT ;
    }
}